version: "3.8"
services:
  storage:
    build:
      context: "storage"
    restart: "always"
    volumes:
      - "./example-deployments:/www/deployments" # TODO: mount volume, remove examples in the long run
  runtime:
    build:
      context: "runtime"
    restart: "always"
    deploy:
      mode: "replicated"
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.runtime.rule=HostRegexp(`.+\\.localhost`)"
    depends_on:
      - "storage"
    environment:
      FUNCTIONS_BLOCKED_NETWORKS: "192.168.1.0/8" # TODO: add more blocked networks
  ingress:
    image: "traefik:v3.0"
    restart: "always"
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
