version: "3.8"
services:
  storage:
    build:
      context: "storage"
    restart: "always"
    volumes:
      - "./storage-data:/deployments" # TODO: make a proper volume not only a bind mount
    labels: # TODO: do not expose storage directly!
      - "traefik.enable=true"
      - "traefik.http.routers.storage.rule=Host(`storage.localhost`)"
  runtime:
    build:
      context: "runtime"
    restart: "always"
    deploy:
      mode: "replicated"
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.runtime.rule=HostRegexp(`.+\\.apps\\.localhost`)"
    depends_on:
      - "storage"
    environment:
      FUNCTIONS_BLOCKED_NETWORKS: "192.168.0.0/16"
  ingress:
    image: "traefik:v3.0"
    restart: "always"
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  storage:
